development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: ENV["PG_USERNAME"]
  password: ENV["PG_PASSWORD"]

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: ENV["PG_USERNAME"]
  password: ENV["PG_PASSWORD"]
